from django.http import HttpResponse

def index(request):
    return HttpResponse("""
<html lang="en" op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?ZTDkdntDAI7DeQT8Qufl">
        <link rel="shortcut icon" href="favicon.ico">
          <link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
        <title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
        <tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com"><img src="y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
                  <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="news">Hacker News</a></b>
                            <a href="newest">new</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <a href="ask">ask</a> | <a href="show">show</a> | <a href="jobs">jobs</a> | <a href="submit">submit</a>            </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                              <a href="login?goto=news">login</a>
                          </span></td>
              </tr></table></td></tr>
<tr id="pagespace" title="" style="height:10px"></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
              <tr class='athing' id='32297760'>
      <td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32297760'href='vote?id=32297760&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://easyrpg.org/" class="titlelink">EasyRPG</a><span class="sitebit comhead"> (<a href="from?site=easyrpg.org"><span class="sitestr">easyrpg.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32297760">153 points</span> by <a href="user?id=tosh" class="hnuser">tosh</a> <span class="age" title="2022-07-31T18:52:44"><a href="item?id=32297760">2 hours ago</a></span> <span id="unv_32297760"></span> | <a href="hide?id=32297760&amp;goto=news">hide</a> | <a href="item?id=32297760">24&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32298137'>
      <td align="right" valign="top" class="title"><span class="rank">2.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32298137'href='vote?id=32298137&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://bret.dk/raspberry-pi-zero-vs-mangopi-mq-pro-benchmarks/" class="titlelink">RISC-V based Single Board Computers are getting there</a><span class="sitebit comhead"> (<a href="from?site=bret.dk"><span class="sitestr">bret.dk</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32298137">75 points</span> by <a href="user?id=bmlw" class="hnuser">bmlw</a> <span class="age" title="2022-07-31T19:39:31"><a href="item?id=32298137">1 hour ago</a></span> <span id="unv_32298137"></span> | <a href="hide?id=32298137&amp;goto=news">hide</a> | <a href="item?id=32298137">20&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32298067'>
      <td align="right" valign="top" class="title"><span class="rank">3.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32298067'href='vote?id=32298067&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://techtinkering.com/2013/03/12/if-only-borland-had-stuck-with-turbo-modula-2-for-cpm/" class="titlelink">If Only Borland Had Stuck with Turbo Modula-2 for CP/M (2013)</a><span class="sitebit comhead"> (<a href="from?site=techtinkering.com"><span class="sitestr">techtinkering.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32298067">47 points</span> by <a href="user?id=nope96" class="hnuser">nope96</a> <span class="age" title="2022-07-31T19:32:13"><a href="item?id=32298067">1 hour ago</a></span> <span id="unv_32298067"></span> | <a href="hide?id=32298067&amp;goto=news">hide</a> | <a href="item?id=32298067">12&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32298058'>
      <td align="right" valign="top" class="title"><span class="rank">4.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32298058'href='vote?id=32298058&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://iximiuz.com/en/posts/kubernetes-vs-virtual-machines/" class="titlelink">Kubernetes Reinvented Virtual Machines (in a good sense)</a><span class="sitebit comhead"> (<a href="from?site=iximiuz.com"><span class="sitestr">iximiuz.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32298058">45 points</span> by <a href="user?id=paulgb" class="hnuser">paulgb</a> <span class="age" title="2022-07-31T19:30:27"><a href="item?id=32298058">1 hour ago</a></span> <span id="unv_32298058"></span> | <a href="hide?id=32298058&amp;goto=news">hide</a> | <a href="item?id=32298058">7&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32296299'>
      <td align="right" valign="top" class="title"><span class="rank">5.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32296299'href='vote?id=32296299&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.ghostscript.com/blog/pdfi.html" class="titlelink">New Ghostscript PDF interpreter</a><span class="sitebit comhead"> (<a href="from?site=ghostscript.com"><span class="sitestr">ghostscript.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32296299">131 points</span> by <a href="user?id=diskmuncher" class="hnuser">diskmuncher</a> <span class="age" title="2022-07-31T15:40:44"><a href="item?id=32296299">5 hours ago</a></span> <span id="unv_32296299"></span> | <a href="hide?id=32296299&amp;goto=news">hide</a> | <a href="item?id=32296299">58&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32296952'>
      <td align="right" valign="top" class="title"><span class="rank">6.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32296952'href='vote?id=32296952&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="item?id=32296952" class="titlelink">LinkedIn is importing job postings it finds online onto company's profiles</a></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32296952">243 points</span> by <a href="user?id=gurchik" class="hnuser">gurchik</a> <span class="age" title="2022-07-31T17:07:48"><a href="item?id=32296952">4 hours ago</a></span> <span id="unv_32296952"></span> | <a href="hide?id=32296952&amp;goto=news">hide</a> | <a href="item?id=32296952">93&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32298801'>
      <td align="right" valign="top" class="title"><span class="rank">7.</span></td>      <td></td><td class="title"><a href="https://www.patterns.app/" class="titlelink" rel="nofollow">Patterns (YC S21) is hiring devs to build the Figma for data</a><span class="sitebit comhead"> (<a href="from?site=patterns.app"><span class="sitestr">patterns.app</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="age" title="2022-07-31T21:01:03"><a href="item?id=32298801">22 minutes ago</a></span> | <a href="hide?id=32298801&amp;goto=news">hide</a>      </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32296603'>
      <td align="right" valign="top" class="title"><span class="rank">8.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32296603'href='vote?id=32296603&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://nicole.express/2022/sega-8-bit-conversion-kit.html" class="titlelink">Converting from the Game Gear to the Master System</a><span class="sitebit comhead"> (<a href="from?site=nicole.express"><span class="sitestr">nicole.express</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32296603">65 points</span> by <a href="user?id=stevekemp" class="hnuser">stevekemp</a> <span class="age" title="2022-07-31T16:23:23"><a href="item?id=32296603">4 hours ago</a></span> <span id="unv_32296603"></span> | <a href="hide?id=32296603&amp;goto=news">hide</a> | <a href="item?id=32296603">7&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32287571'>
      <td align="right" valign="top" class="title"><span class="rank">9.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32287571'href='vote?id=32287571&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://support.usr.com/support/6000/6000-ug/two.html" class="titlelink">How a cable modem works (c. 2002)</a><span class="sitebit comhead"> (<a href="from?site=usr.com"><span class="sitestr">usr.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32287571">26 points</span> by <a href="user?id=jqcoffey" class="hnuser">jqcoffey</a> <span class="age" title="2022-07-30T15:31:47"><a href="item?id=32287571">2 hours ago</a></span> <span id="unv_32287571"></span> | <a href="hide?id=32287571&amp;goto=news">hide</a> | <a href="item?id=32287571">4&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32294430'>
      <td align="right" valign="top" class="title"><span class="rank">10.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32294430'href='vote?id=32294430&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://scottaaronson.blog/?p=208" class="titlelink">Shor, I’ll do it</a><span class="sitebit comhead"> (<a href="from?site=scottaaronson.blog"><span class="sitestr">scottaaronson.blog</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32294430">275 points</span> by <a href="user?id=monort" class="hnuser">monort</a> <span class="age" title="2022-07-31T09:38:08"><a href="item?id=32294430">11 hours ago</a></span> <span id="unv_32294430"></span> | <a href="hide?id=32294430&amp;goto=news">hide</a> | <a href="item?id=32294430">40&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32297559'>
      <td align="right" valign="top" class="title"><span class="rank">11.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32297559'href='vote?id=32297559&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://deck.rocks" class="titlelink">Show HN: Generate pitch decks using GPT3 from 1-line ideas</a><span class="sitebit comhead"> (<a href="from?site=deck.rocks"><span class="sitestr">deck.rocks</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32297559">28 points</span> by <a href="user?id=diwank" class="hnuser">diwank</a> <span class="age" title="2022-07-31T18:30:20"><a href="item?id=32297559">2 hours ago</a></span> <span id="unv_32297559"></span> | <a href="hide?id=32297559&amp;goto=news">hide</a> | <a href="item?id=32297559">6&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32295309'>
      <td align="right" valign="top" class="title"><span class="rank">12.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32295309'href='vote?id=32295309&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.leadedsolder.com/2021/08/10/ti83-lcd-ribbon-repair.html" class="titlelink">TI-83 Plus One More</a><span class="sitebit comhead"> (<a href="from?site=leadedsolder.com"><span class="sitestr">leadedsolder.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32295309">110 points</span> by <a href="user?id=rez10191" class="hnuser">rez10191</a> <span class="age" title="2022-07-31T13:20:07"><a href="item?id=32295309">8 hours ago</a></span> <span id="unv_32295309"></span> | <a href="hide?id=32295309&amp;goto=news">hide</a> | <a href="item?id=32295309">61&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32298183'>
      <td align="right" valign="top" class="title"><span class="rank">13.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32298183'href='vote?id=32298183&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.vox.com/recode/23282640/leaked-internal-memo-reveals-amazons-anti-union-strategies-teamsters" class="titlelink">Amazon’s plan to “neutralize” unions with ex-inmates and “vulnerable students”</a><span class="sitebit comhead"> (<a href="from?site=vox.com"><span class="sitestr">vox.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32298183">66 points</span> by <a href="user?id=hownottowrite" class="hnuser">hownottowrite</a> <span class="age" title="2022-07-31T19:45:54"><a href="item?id=32298183">1 hour ago</a></span> <span id="unv_32298183"></span> | <a href="hide?id=32298183&amp;goto=news">hide</a> | <a href="item?id=32298183">20&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32297936'>
      <td align="right" valign="top" class="title"><span class="rank">14.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32297936'href='vote?id=32297936&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://nassimcomics.substack.com/p/a-tutorial-like-you-have-never-seen" class="titlelink">A tutorial like you have never seen before</a><span class="sitebit comhead"> (<a href="from?site=nassimcomics.substack.com"><span class="sitestr">nassimcomics.substack.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32297936">15 points</span> by <a href="user?id=nassimsoftware" class="hnuser">nassimsoftware</a> <span class="age" title="2022-07-31T19:14:40"><a href="item?id=32297936">2 hours ago</a></span> <span id="unv_32297936"></span> | <a href="hide?id=32297936&amp;goto=news">hide</a> | <a href="item?id=32297936">8&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32278773'>
      <td align="right" valign="top" class="title"><span class="rank">15.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32278773'href='vote?id=32278773&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.105.9288&amp;rep=rep1&amp;type=pdf" class="titlelink">Modula-2 and Oberon (2007) [pdf]</a><span class="sitebit comhead"> (<a href="from?site=psu.edu"><span class="sitestr">psu.edu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32278773">22 points</span> by <a href="user?id=Jtsummers" class="hnuser">Jtsummers</a> <span class="age" title="2022-07-29T16:14:03"><a href="item?id=32278773">3 hours ago</a></span> <span id="unv_32278773"></span> | <a href="hide?id=32278773&amp;goto=news">hide</a> | <a href="item?id=32278773">17&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32294528'>
      <td align="right" valign="top" class="title"><span class="rank">16.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32294528'href='vote?id=32294528&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://news.mit.edu/2022/study-finds-wikipedia-influences-judicial-behavior-0727" class="titlelink">Study finds Wikipedia influences judicial behavior</a><span class="sitebit comhead"> (<a href="from?site=news.mit.edu"><span class="sitestr">news.mit.edu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32294528">178 points</span> by <a href="user?id=drewem" class="hnuser">drewem</a> <span class="age" title="2022-07-31T10:06:55"><a href="item?id=32294528">11 hours ago</a></span> <span id="unv_32294528"></span> | <a href="hide?id=32294528&amp;goto=news">hide</a> | <a href="item?id=32294528">85&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32294928'>
      <td align="right" valign="top" class="title"><span class="rank">17.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32294928'href='vote?id=32294928&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://paulsellers.com/2013/06/hitachi-plug-cutter-works-perfeclty-in-hand-held-drills/" class="titlelink">Hitachi Wood Plug Cutter Works Perfectly in Hand Held Drills (2013)</a><span class="sitebit comhead"> (<a href="from?site=paulsellers.com"><span class="sitestr">paulsellers.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32294928">104 points</span> by <a href="user?id=walterbell" class="hnuser">walterbell</a> <span class="age" title="2022-07-31T11:50:22"><a href="item?id=32294928">9 hours ago</a></span> <span id="unv_32294928"></span> | <a href="hide?id=32294928&amp;goto=news">hide</a> | <a href="item?id=32294928">47&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32285588'>
      <td align="right" valign="top" class="title"><span class="rank">18.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32285588'href='vote?id=32285588&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.youtube.com/watch?v=m53H0pO2FD4" class="titlelink">Inside an IBM AS/400 eSeries Factory [video]</a><span class="sitebit comhead"> (<a href="from?site=youtube.com"><span class="sitestr">youtube.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32285588">16 points</span> by <a href="user?id=grunthos" class="hnuser">grunthos</a> <span class="age" title="2022-07-30T10:09:33"><a href="item?id=32285588">3 hours ago</a></span> <span id="unv_32285588"></span> | <a href="hide?id=32285588&amp;goto=news">hide</a> | <a href="item?id=32285588">7&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32285375'>
      <td align="right" valign="top" class="title"><span class="rank">19.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32285375'href='vote?id=32285375&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://blog.pragmaticengineer.com/want-to-start-a-startup-sell-something-online/" class="titlelink">Want to Start a Startup, as a Software Engineer? Sell Something Online</a><span class="sitebit comhead"> (<a href="from?site=pragmaticengineer.com"><span class="sitestr">pragmaticengineer.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32285375">203 points</span> by <a href="user?id=yamrzou" class="hnuser">yamrzou</a> <span class="age" title="2022-07-30T09:07:40"><a href="item?id=32285375">14 hours ago</a></span> <span id="unv_32285375"></span> | <a href="hide?id=32285375&amp;goto=news">hide</a> | <a href="item?id=32285375">70&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32296783'>
      <td align="right" valign="top" class="title"><span class="rank">20.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32296783'href='vote?id=32296783&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.devraven.io" class="titlelink">Show HN: DevRaven – Monitoring for Developers</a><span class="sitebit comhead"> (<a href="from?site=devraven.io"><span class="sitestr">devraven.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32296783">27 points</span> by <a href="user?id=kc10" class="hnuser">kc10</a> <span class="age" title="2022-07-31T16:46:53"><a href="item?id=32296783">4 hours ago</a></span> <span id="unv_32296783"></span> | <a href="hide?id=32296783&amp;goto=news">hide</a> | <a href="item?id=32296783">24&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32297739'>
      <td align="right" valign="top" class="title"><span class="rank">21.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32297739'href='vote?id=32297739&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://www.citrobe.org/br70s.htm" class="titlelink">Citroën Catalogs from the 70s</a><span class="sitebit comhead"> (<a href="from?site=citrobe.org"><span class="sitestr">citrobe.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32297739">50 points</span> by <a href="user?id=dayve" class="hnuser">dayve</a> <span class="age" title="2022-07-31T18:50:16"><a href="item?id=32297739">2 hours ago</a></span> <span id="unv_32297739"></span> | <a href="hide?id=32297739&amp;goto=news">hide</a> | <a href="item?id=32297739">47&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32295674'>
      <td align="right" valign="top" class="title"><span class="rank">22.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32295674'href='vote?id=32295674&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.google.com/search?q=6+minute+timer" class="titlelink">Google Timer is gone</a><span class="sitebit comhead"> (<a href="from?site=google.com"><span class="sitestr">google.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32295674">443 points</span> by <a href="user?id=wuschel" class="hnuser">wuschel</a> <span class="age" title="2022-07-31T14:23:28"><a href="item?id=32295674">6 hours ago</a></span> <span id="unv_32295674"></span> | <a href="hide?id=32295674&amp;goto=news">hide</a> | <a href="item?id=32295674">262&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32280756'>
      <td align="right" valign="top" class="title"><span class="rank">23.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32280756'href='vote?id=32280756&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.science.org/content/blog-post/faked-crystallography" class="titlelink">Faked Crystallography</a><span class="sitebit comhead"> (<a href="from?site=science.org"><span class="sitestr">science.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32280756">61 points</span> by <a href="user?id=mhb" class="hnuser">mhb</a> <span class="age" title="2022-07-29T19:19:19"><a href="item?id=32280756">6 hours ago</a></span> <span id="unv_32280756"></span> | <a href="hide?id=32280756&amp;goto=news">hide</a> | <a href="item?id=32280756">44&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32295394'>
      <td align="right" valign="top" class="title"><span class="rank">24.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32295394'href='vote?id=32295394&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://gitlab.com/ipcalc/ipcalc" class="titlelink">Ipcalc – Command line CIDR calculator with IPv6 support</a><span class="sitebit comhead"> (<a href="from?site=gitlab.com/ipcalc"><span class="sitestr">gitlab.com/ipcalc</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32295394">63 points</span> by <a href="user?id=jaden" class="hnuser">jaden</a> <span class="age" title="2022-07-31T13:38:41"><a href="item?id=32295394">7 hours ago</a></span> <span id="unv_32295394"></span> | <a href="hide?id=32295394&amp;goto=news">hide</a> | <a href="item?id=32295394">24&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32295251'>
      <td align="right" valign="top" class="title"><span class="rank">25.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32295251'href='vote?id=32295251&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://thereader.mitpress.mit.edu/when-cities-treated-cars-as-dangerous-intruders/" class="titlelink">When cities treated cars as dangerous intruders</a><span class="sitebit comhead"> (<a href="from?site=mitpress.mit.edu"><span class="sitestr">mitpress.mit.edu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32295251">298 points</span> by <a href="user?id=pseudolus" class="hnuser">pseudolus</a> <span class="age" title="2022-07-31T13:07:44"><a href="item?id=32295251">8 hours ago</a></span> <span id="unv_32295251"></span> | <a href="hide?id=32295251&amp;goto=news">hide</a> | <a href="item?id=32295251">285&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32296984'>
      <td align="right" valign="top" class="title"><span class="rank">26.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32296984'href='vote?id=32296984&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://everythingisamazing.substack.com/p/the-worst-dam-idea-in-the-world" class="titlelink">The worst dam idea: evaporating the Mediterranean to power Europe</a><span class="sitebit comhead"> (<a href="from?site=everythingisamazing.substack.com"><span class="sitestr">everythingisamazing.substack.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32296984">81 points</span> by <a href="user?id=bandibus" class="hnuser">bandibus</a> <span class="age" title="2022-07-31T17:12:46"><a href="item?id=32296984">4 hours ago</a></span> <span id="unv_32296984"></span> | <a href="hide?id=32296984&amp;goto=news">hide</a> | <a href="item?id=32296984">43&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32296272'>
      <td align="right" valign="top" class="title"><span class="rank">27.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32296272'href='vote?id=32296272&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.apa.org/news/press/releases/2022/07/thoughts-mind-wander" class="titlelink">Put down devices, let your mind wander, study suggests</a><span class="sitebit comhead"> (<a href="from?site=apa.org"><span class="sitestr">apa.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32296272">20 points</span> by <a href="user?id=chazeon" class="hnuser">chazeon</a> <span class="age" title="2022-07-31T15:37:27"><a href="item?id=32296272">5 hours ago</a></span> <span id="unv_32296272"></span> | <a href="hide?id=32296272&amp;goto=news">hide</a> | <a href="item?id=32296272">4&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32279897'>
      <td align="right" valign="top" class="title"><span class="rank">28.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32279897'href='vote?id=32279897&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://blog.chriszacharias.com/page-weight-matters" class="titlelink">Page Weight Matters (2012)</a><span class="sitebit comhead"> (<a href="from?site=chriszacharias.com"><span class="sitestr">chriszacharias.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32279897">125 points</span> by <a href="user?id=Tomte" class="hnuser">Tomte</a> <span class="age" title="2022-07-29T17:51:02"><a href="item?id=32279897">13 hours ago</a></span> <span id="unv_32279897"></span> | <a href="hide?id=32279897&amp;goto=news">hide</a> | <a href="item?id=32279897">50&nbsp;comments</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32295291'>
      <td align="right" valign="top" class="title"><span class="rank">29.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32295291'href='vote?id=32295291&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://github.com/sysrpl/Tiny.Sim" class="titlelink">Codebot.Tiny – A tiny library for rendering animated 2D/3D graphics</a><span class="sitebit comhead"> (<a href="from?site=github.com/sysrpl"><span class="sitestr">github.com/sysrpl</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32295291">38 points</span> by <a href="user?id=wagslane" class="hnuser">wagslane</a> <span class="age" title="2022-07-31T13:17:00"><a href="item?id=32295291">8 hours ago</a></span> <span id="unv_32295291"></span> | <a href="hide?id=32295291&amp;goto=news">hide</a> | <a href="item?id=32295291">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
                <tr class='athing' id='32278663'>
      <td align="right" valign="top" class="title"><span class="rank">30.</span></td>      <td valign="top" class="votelinks"><center><a id='up_32278663'href='vote?id=32278663&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://words.filippo.io/dispatches/post-quantum-age/" class="titlelink">KEMs and Post-Quantum Age</a><span class="sitebit comhead"> (<a href="from?site=filippo.io"><span class="sitestr">filippo.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
        <span class="score" id="score_32278663">31 points</span> by <a href="user?id=hasheddan" class="hnuser">hasheddan</a> <span class="age" title="2022-07-29T16:06:27"><a href="item?id=32278663">5 hours ago</a></span> <span id="unv_32278663"></span> | <a href="hide?id=32278663&amp;goto=news">hide</a> | <a href="item?id=32278663">discuss</a>              </td></tr>
      <tr class="spacer" style="height:5px"></tr>
            <tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td>
      <td class='title'><a href='news?p=2' class='morelink' rel='next'>More</a></td>    </tr>
  </table>
</td></tr>
<tr><td><img src="s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
        | <a href="newsfaq.html">FAQ</a>
        | <a href="lists">Lists</a>
        | <a href="https://github.com/HackerNews/API">API</a>
        | <a href="security.html">Security</a>
        | <a href="http://www.ycombinator.com/legal/">Legal</a>
        | <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
        | <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
          <input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
            </center></td></tr>
      </table></center></body>
      <script type='text/javascript' src='hn.js?ZTDkdntDAI7DeQT8Qufl'></script>
  </html>
""")
